version: '3.8'

services:
  elixir_app:
    image: leotf159/bank_digital:2.0
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh docker_dev_start.sh
    environment:
      PORT: "4000"  # Porta padrão para o servidor Phoenix
      HOST: "postgresql_db"
      DATABASE_URL: "postgres://postgres:postgres@postgresql_db:5432/bank_digital_dev"
    depends_on:
      - postgresql_db
    ports:
      - "4000:4000"
    networks:
      - bank_network

  postgresql_db:
    image: postgres:13
    container_name: postgresql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_digital_dev
      HOST: postgresql_db
      DATABASE_URL: "postgres://postgres:postgres@postgresql_db:5432/bank_digital_dev"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgresql_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bank_network

networks:
  bank_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
