# Dockerfile.test
FROM elixir:1.16.2-otp-25

WORKDIR /app

RUN apt-get update && \
    apt-get install -y postgresql-client


COPY . .

RUN mix local.hex --force && \
    mix local.rebar --force

RUN mix deps.get

CMD ["mix", "test"]
